all:
  children:
    managers:
      hosts:
        ubuntu-manager:
          ansible_host: 192.168.10.118
          ansible_user: maksi

    workers:
      hosts:
        ubuntu-worker-1:
          ansible_host: 192.168.10.119
          ansible_user: maksi
        ubuntu-worker-2:
          ansible_host: 192.168.10.120
          ansible_user: maksi